# Generated by Django 2.1.5 on 2019-08-07 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20190807_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shop.Product'),
        ),
    ]
